jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: List root directory
        run: ls

      - name: List src/my_chatapplication directory
        working-directory: src/my_chatapplication
        run: ls

      - name: Compile main classes
        working-directory: src/my_chatapplication
        run: |
          javac -cp "../../test/resources/junit-platform-console-standalone-1.6.0.jar:../../test/resources/json-simple-1.1.1.jar" \
          *.java

      - name: Copy compiled classes to test resources
        run: |
          cp *.class ../test_resources/

      - name: List test_resources directory
        working-directory: test_resources
        run: ls

      - name: Compile test classes
        working-directory: test/resources
        run: |
          javac -cp "../../test/resources/junit-platform-console-standalone-1.6.0.jar:../../test/resources/json-simple-1.1.1.jar" \
          *.java

      - name: Run tests and generate report
        working-directory: test/resources
        run: |
          java -jar ../../test/resources/junit-platform-console-standalone-1.6.0.jar \
          --class-path ../my_chatapplication \
          --select-class my_chatapplication.MyChatAppTest \
         reports-dir=reports
